### ISSUE TITLE
Problemas na tese

### ISSUE THREAD

**Issue by GoogleCodeExporter** [brunoduartec/duartec-projects#1]
```
Resolver problemas na tese


```

Original issue reported on code.google.com by `bruno.duartec` on 29 Jan 2015 at 11:21

Attachments:
- [tese-issues.txt](https://storage.googleapis.com/google-code-attachments/duartec-projects/issue-1/comment-0/tese-issues.txt)

**Comment by brunoduartec** [comment]
The issue was solved
